# Auto-labeling configuration for pull requests

'area: core':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/QuickApiMapper.Contracts/**/*'
      - 'src/QuickApiMapper.Application/**/*'

'area: behaviors':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/QuickApiMapper.Behaviors/**/*'

'area: transformers':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/QuickApiMapper.StandardTransformers/**/*'
      - 'src/QuickApiMapper.CustomTransformers/**/*'

'area: persistence':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/QuickApiMapper.Persistence.*/**/*'

'area: message-capture':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/QuickApiMapper.MessageCapture.*/**/*'

'area: extensions':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/QuickApiMapper.Extensions.*/**/*'

'area: api':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/QuickApiMapper.Web/**/*'
      - 'src/QuickApiMapper.Management.Api/**/*'

'area: ui':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/QuickApiMapper.Designer.Web/**/*'

'area: documentation':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

'area: tests':
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**/*'

'area: ci/cd':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - 'azure-pipelines.yml'

'dependencies':
  - changed-files:
    - any-glob-to-any-file:
      - '**/packages.lock.json'
      - 'Directory.Packages.props'
      - '**/*.csproj'
