// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuickApiMapper.Persistence.PostgreSQL;

#nullable disable

namespace QuickApiMapper.Persistence.PostgreSQL.Migrations
{
    [DbContext(typeof(QuickApiMapperDbContext))]
    [Migration("20260108050526_AddIntegrationToggleFields")]
    partial class AddIntegrationToggleFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.FieldMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Destination")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("IntegrationMappingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationMappingId", "Order");

                    b.ToTable("fieldmappings");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.GlobalToggleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_global_toggles_key");

                    b.ToTable("global_toggles", (string)null);
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.GrpcConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IntegrationMappingId")
                        .HasColumnType("uuid");

                    b.Property<string>("MethodName")
                        .HasColumnType("text");

                    b.Property<string>("Package")
                        .HasColumnType("text");

                    b.Property<string>("ProtoFile")
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationMappingId")
                        .IsUnique();

                    b.ToTable("grpcconfigurations");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DestinationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DestinationUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DispatchFor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EnableInput")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableMessageCapture")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableOutput")
                        .HasColumnType("boolean");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("integrationmappings");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.RabbitMqConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationExchange")
                        .HasColumnType("text");

                    b.Property<string>("DestinationRoutingKey")
                        .HasColumnType("text");

                    b.Property<string>("HostName")
                        .HasColumnType("text");

                    b.Property<Guid>("IntegrationMappingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("SourceExchange")
                        .HasColumnType("text");

                    b.Property<string>("SourceQueue")
                        .HasColumnType("text");

                    b.Property<string>("SourceRoutingKey")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("VirtualHost")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationMappingId")
                        .IsUnique();

                    b.ToTable("rabbitmqconfigurations");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.ServiceBusConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("text");

                    b.Property<string>("DestinationQueue")
                        .HasColumnType("text");

                    b.Property<string>("DestinationTopic")
                        .HasColumnType("text");

                    b.Property<Guid>("IntegrationMappingId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxConcurrentCalls")
                        .HasColumnType("integer");

                    b.Property<string>("MessageType")
                        .HasColumnType("text");

                    b.Property<string>("SourceQueue")
                        .HasColumnType("text");

                    b.Property<string>("SourceSubscription")
                        .HasColumnType("text");

                    b.Property<string>("SourceTopic")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationMappingId")
                        .IsUnique();

                    b.ToTable("servicebusconfigurations");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.SoapConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyWrapperFieldXPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("IntegrationMappingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationMappingId")
                        .IsUnique();

                    b.ToTable("soapconfigurations");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.SoapFieldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attributes")
                        .HasColumnType("jsonb");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Namespace")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Prefix")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SoapConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("XPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SoapConfigId", "Order");

                    b.ToTable("soapfields");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.StaticValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IntegrationMappingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsGlobal");

                    b.HasIndex("IntegrationMappingId", "Key");

                    b.ToTable("staticvalues");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.TransformerConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Arguments")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("FieldMappingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FieldMappingId", "Order");

                    b.ToTable("transformers");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.FieldMappingEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", "IntegrationMapping")
                        .WithMany("FieldMappings")
                        .HasForeignKey("IntegrationMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationMapping");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.GrpcConfigEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", "IntegrationMapping")
                        .WithOne("GrpcConfig")
                        .HasForeignKey("QuickApiMapper.Persistence.Abstractions.Models.GrpcConfigEntity", "IntegrationMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationMapping");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.RabbitMqConfigEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", "IntegrationMapping")
                        .WithOne("RabbitMqConfig")
                        .HasForeignKey("QuickApiMapper.Persistence.Abstractions.Models.RabbitMqConfigEntity", "IntegrationMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationMapping");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.ServiceBusConfigEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", "IntegrationMapping")
                        .WithOne("ServiceBusConfig")
                        .HasForeignKey("QuickApiMapper.Persistence.Abstractions.Models.ServiceBusConfigEntity", "IntegrationMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationMapping");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.SoapConfigEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", "IntegrationMapping")
                        .WithOne("SoapConfig")
                        .HasForeignKey("QuickApiMapper.Persistence.Abstractions.Models.SoapConfigEntity", "IntegrationMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationMapping");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.SoapFieldEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.SoapConfigEntity", "SoapConfig")
                        .WithMany("Fields")
                        .HasForeignKey("SoapConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoapConfig");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.StaticValueEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", "IntegrationMapping")
                        .WithMany("StaticValues")
                        .HasForeignKey("IntegrationMappingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IntegrationMapping");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.TransformerConfigEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.FieldMappingEntity", "FieldMapping")
                        .WithMany("Transformers")
                        .HasForeignKey("FieldMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldMapping");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.FieldMappingEntity", b =>
                {
                    b.Navigation("Transformers");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", b =>
                {
                    b.Navigation("FieldMappings");

                    b.Navigation("GrpcConfig");

                    b.Navigation("RabbitMqConfig");

                    b.Navigation("ServiceBusConfig");

                    b.Navigation("SoapConfig");

                    b.Navigation("StaticValues");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.SoapConfigEntity", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
