// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickApiMapper.Persistence.SQLite;

#nullable disable

namespace QuickApiMapper.Persistence.SQLite.Migrations
{
    [DbContext(typeof(QuickApiMapperSqliteDbContext))]
    [Migration("20260108050837_SeedSampleIntegrations")]
    partial class SeedSampleIntegrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.FieldMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IntegrationMappingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationMappingId");

                    b.ToTable("FieldMappings");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.GlobalToggleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("GlobalToggles");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.GrpcConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IntegrationMappingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Package")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtoFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationMappingId")
                        .IsUnique();

                    b.ToTable("GrpcConfigurations");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DispatchFor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableInput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableMessageCapture")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableOutput")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IntegrationMappings");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.RabbitMqConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationExchange")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationRoutingKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IntegrationMappingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceExchange")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceQueue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRoutingKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("VirtualHost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationMappingId")
                        .IsUnique();

                    b.ToTable("RabbitMqConfigurations");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.ServiceBusConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationQueue")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationTopic")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IntegrationMappingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxConcurrentCalls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceQueue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSubscription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTopic")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationMappingId")
                        .IsUnique();

                    b.ToTable("ServiceBusConfigurations");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.SoapConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyWrapperFieldXPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IntegrationMappingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationMappingId")
                        .IsUnique();

                    b.ToTable("SoapConfigurations");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.SoapFieldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Attributes")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Namespace")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SoapConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("XPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SoapConfigId", "Order");

                    b.ToTable("SoapFields");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.StaticValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IntegrationMappingId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationMappingId");

                    b.ToTable("StaticValues");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.TransformerConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FieldMappingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FieldMappingId", "Order");

                    b.ToTable("Transformers");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.FieldMappingEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", "IntegrationMapping")
                        .WithMany("FieldMappings")
                        .HasForeignKey("IntegrationMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationMapping");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.GrpcConfigEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", "IntegrationMapping")
                        .WithOne("GrpcConfig")
                        .HasForeignKey("QuickApiMapper.Persistence.Abstractions.Models.GrpcConfigEntity", "IntegrationMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationMapping");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.RabbitMqConfigEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", "IntegrationMapping")
                        .WithOne("RabbitMqConfig")
                        .HasForeignKey("QuickApiMapper.Persistence.Abstractions.Models.RabbitMqConfigEntity", "IntegrationMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationMapping");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.ServiceBusConfigEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", "IntegrationMapping")
                        .WithOne("ServiceBusConfig")
                        .HasForeignKey("QuickApiMapper.Persistence.Abstractions.Models.ServiceBusConfigEntity", "IntegrationMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationMapping");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.SoapConfigEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", "IntegrationMapping")
                        .WithOne("SoapConfig")
                        .HasForeignKey("QuickApiMapper.Persistence.Abstractions.Models.SoapConfigEntity", "IntegrationMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationMapping");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.SoapFieldEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.SoapConfigEntity", "SoapConfig")
                        .WithMany("Fields")
                        .HasForeignKey("SoapConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoapConfig");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.StaticValueEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", "IntegrationMapping")
                        .WithMany("StaticValues")
                        .HasForeignKey("IntegrationMappingId");

                    b.Navigation("IntegrationMapping");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.TransformerConfigEntity", b =>
                {
                    b.HasOne("QuickApiMapper.Persistence.Abstractions.Models.FieldMappingEntity", "FieldMapping")
                        .WithMany("Transformers")
                        .HasForeignKey("FieldMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldMapping");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.FieldMappingEntity", b =>
                {
                    b.Navigation("Transformers");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.IntegrationMappingEntity", b =>
                {
                    b.Navigation("FieldMappings");

                    b.Navigation("GrpcConfig");

                    b.Navigation("RabbitMqConfig");

                    b.Navigation("ServiceBusConfig");

                    b.Navigation("SoapConfig");

                    b.Navigation("StaticValues");
                });

            modelBuilder.Entity("QuickApiMapper.Persistence.Abstractions.Models.SoapConfigEntity", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
